<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class StoriesExcelExportController extends Controller
{
    public function download(Request $request, string $fileName)
    {
        // Basic hardening: allow only .xlsx files generated by the action.
        if (!str_ends_with($fileName, '.xlsx') || str_contains($fileName, '..') || str_contains($fileName, '/')) {
            abort(404);
        }

        if (!Storage::disk('public')->exists($fileName)) {
            abort(404);
        }

        // Disk "public" is local and rooted at storage/app/public (see config/filesystems.php).
        $path = storage_path('app/public/' . $fileName);

        return response()->download($path, $fileName);
    }
}

